name: Update Submodules

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'  # Run every day at midnight
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Update ai4-mlflow submodule
      run: |
        mlflow_commit=$(curl -s "https://api.github.com/repos/m-team-kit/mlflow-auth-gui/commits/main" | jq -r '.sha')
        echo "MLflow submodule latest commit: $mlflow_commit"
        git submodule update --remote -- ai4-mlflow  # Update specific submodule
        git -C ai4-mlflow checkout $mlflow_commit  # Checkout specific commit
      
    - name: Update frouros submodule
      run: |
        frouros_commit=$(curl -s "https://api.github.com/repos/IFCA-Advanced-Computing/frouros/commits/main" | jq -r '.sha')
        echo "Frouros submodule latest commit: $frouros_commit"
        git submodule update --remote -- frouros  # Update specific submodule
        git -C frouros checkout $frouros_commit  # Checkout specific commit

    - name: Check for Changes, Commit/Push
      run: |
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit. Exiting gracefully."
          exit 0
        else
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update submodule commits"
          git push
        fi
     


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
