name: Update Submodules

on:
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Update mlflow submodule
      run: |
        mlflow_commit=$(curl -s "https://api.github.com/repos/ai4os/ai4-mlops/commits/main" | jq -r '.sha')
        echo "MLflow submodule latest commit: $mlflow_commit"
        git submodule update --init --remote # Initialize and update submodule
        cd ai4-mlops
        git checkout $mlflow_commit
        cd ..
      
    - name: Update frouros submodule
      run: |
        frouros_commit=$(curl -s "https://api.github.com/repos/IFCA-Advanced-Computing/frouros/commits/main" | jq -r '.sha')
        echo "Frouros submodule latest commit: $frouros_commit"
        git submodule update --init --remote
        cd frouros
        git checkout $frouros_commit
        cd ..
     
    - name: Commit and Push Changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update submodule commits"
        git push

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
